<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<title>A Syndicate In Supporting Women And Children Initiative</title>
<link rel="shortcut icon" href="images/icon.ico" type="image/x-icon" />
<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="ngo,Syndicate In Supporting Women And Children Initiative, Nigeria" />
<meta name="keywords" content="Education, Women,Children,Health,Women Empowerment,Syndicate,Adolescent Girl Effect Projects,Justice And Peace In Nigeria" />
<link href='http://fonts.googleapis.com/css?family=Playball' rel='stylesheet' type='text/css'>   
<!--slider-->
<script src="sliderengine/jquery.js"></script>
    <script src="sliderengine/amazingslider.js"></script>
    <script src="sliderengine/initslider-1.js"></script>
</head>
<body>
<div class="header-bg">
	<div class="wrap"> 
		<div class="h-bg">
			<div class="total">
				<div class="header">
					<div class="box_header_user_menu">
						<ul class="user_menu"><li class="act first"><a href="index.php"><div class="button-t"><span>HOME</span></div></a></li><li class=""><a href="contact.php"><div class="button-t"><span>CONTACT</span></div></a></li><li class="last"><a href=""><div class="button-t"><span></span></div></a><a href="news.php"><div class="button-t"><span><marquee onhover="black" scrollamount="1" scrolldelay="1" onmouseover="stop();" onmouseout="start();"><img src="images/news.png" height="50px" width="100px" /></marquee></span></div></a></li><li class=""></li></ul>
					</div>
					<div class="header-right">
						<ul class="follow_icon">
							<li><a href="#"><img src="images/icon.png" alt=""/></a></li>
							<li><a href="#"><img src="images/icon1.png" alt=""/></a></li>
							<li><a href="#"><img src="images/icon2.png" alt=""/></a></li>
							<li><a href="#"><img src="images/icon3.png" alt=""/></a></li>
						</ul>
					</div><div class="clear"></div> 
				  <div class="header-bot">
						<div class="logo">
							<a href="index.php"><img src="images/ban.jpg" alt="" width="361" height="72"/></a>
					  </div>
						<div class="search">
						    <input type="text" class="textbox" value="" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '';}">
						    <button class="gray-button"><span>Search</span></button>
				       </div>
					<div class="clear"></div> 
				</div>		
		</div>	
		<div class="menu"> 	
			<div class="top-nav"> 
					<ul>
						
						<li><a href="about.php">ABOUT </a></li>
						<li><a href="#">BOARD OF TRUSTEES</a></li>
						<li><a href="prog.php">PROGRAM AREAS</a></li>
						<li><a href="media.php">MEDIA CENTRE</a></li>
                        <li><a href="#">DONATIONS</a></li>
                        <b><h1 style='color:white; font-style:italic; margin-top:8px; margin-bottom:8px; font-size:20px; text-align:center;'></h1></b>
					</ul>
					<div class="clear"></div> 
				</div>