
<div class="header-para">
				<div class="categories">
				  <div class="box-title">
				  
				  
					<h1><span class="title-icon"></span><a href="">NEWS</a></h1></div>
					<h3>NEWS TITLE 1</h3>
					<img src='images/ado2.jpg'>
                   <h4>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx<br>xxxxxxxxxxxxxxxxxxxxxxxxxx<br>xxxxxxxxxxx</h4>
				 			 
				 <h3>NEWS TITLE 2</h3>
					<img src='images/ado2.jpg'>
                   <h4>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx<br>xxxxxxxxxxxxxxxxxxxxxxxxxx<br>xxxxxxxxxxx</h4>
				 <p>&nbsp;</p>	  
				 <div class="box-title"> 
				  
					<h1><span class="title-icon"></span><a href="">CORE AREAS OF WORK</a></h1>
				</div>
				
				<p><img src="images/tic.png" width="27" height="19"> EDUCATION </p></br>
               <p><img src="images/tic.png" width="27" height="19">HEALTH </p></br>
	           <p><img src="images/tic.png" width="27" height="19">WOMEN EMPOWERMENT</p></br>
              <p><img src="images/tic.png" width="27" height="19">ADOLESCENT GIRL EFFECT PROJECTS</p> </br>
              <p><img src="images/tic.png" width="27" height="19">JUSTICE AND PEACE</p></br>
				  
				<div class="section group example">
					<div class="col_1_of_2 span_1_of_2">
					  
	 				</div>
					
		   		 </div>
				<div class="clear"></div>
				</div>
	</div>
	